Add support for multiple apptainer images + TF 2.8 def file (#54)
Co-authored-by: Eugen Beck <curufinwe@users.noreply.github.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -112,6 +112,18 @@ configure_i6 () {
     enable_module "CORE_CACHE_MANAGER"
 }
 
+apply_apptainer_setup() {
+    BASE_DIR=$(dirname "$0")
+    FULL_PATH=$BASE_DIR/apptainer/$1/setup_makefiles.sh
+    if [ -f $FULL_PATH ] ; then
+        echo "Set up makefiles via $FULL_PATH"
+        $FULL_PATH
+    else
+        echo "Error: Setup-script $FULL_PATH does not exist!"
+        exit 1
+    fi
+}
+
 
 show_help(){
     cat <<EOF
@@ -129,6 +141,10 @@ General options:
   --i6                                  configures RASR for a default i6 build,
                                         including default modules and tensorflow path.
                                         Please use this always as first argument.
+  --apptainer-setup=<VERSION_NAME>      apply the setup-script in
+                                        apptainer/<VERSION_NAME>/setup_makefiles.sh
+                                        to enable compilation with the image
+                                        given by apptainer/<VERSION_NAME>/image.def
 GCC Options:
   --set-march                           set the target architecture to compile for
                                         (see: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html)
@@ -153,6 +169,11 @@ for i in "$@"; do
             ;;
         --i6)
             configure_i6
+            shift
+            ;;
+        --apptainer-setup=*)
+            VERSION_NAME="${i#*=}"
+            apply_apptainer_setup $VERSION_NAME
             shift
             ;;
         --set-tensorflow=*)
